### ISSUE TITLE
Python 3.6 and ORM determinism

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-perf-rec#12]
If I'm reading the Python 3.6 release notes correctly, it will make the ORM deterministic automatically since kwarg dicts will be iterated in order. Maybe test this and make the ORM patching only happen on Python < 3.6.

**Comment by auvipy** [comment]
you got it right I believe python 3.6 <3

**Comment by adamchainz** [comment]
So this doesn't quite work as the ordering that Python 3.6 uses is not the same ordering that we're currently forcing, so just removing the patches as they stand will make everyone's tests on 3.6 look broken and need rebuilding. Also if we only did the patch on 3.6+ then upgrading from <3.6 to 3.6+ would make tests break.

Doing this wouldn't really be much of a gain until everyone in the world is Python 3.6+.

**Comment by PeterJCLaw** [comment]
Would it be worth putting in place an upgrade path where users can opt to not having the patching, so that those who know they're on 3.6+ for the future can start to migrate?

Alternatively/additionally, if it's possible to match the ordering Python 3.6 gives (I'm guessing possibly not?) offer that (via an option) too?

**Comment by adamchainz** [comment]
Imo, not worth it. Once this supports Django 3.0+ only, every user will be on Python 3.6+, and I'll push a breaking release asking users to rebuild their record files.

**Comment by adamchainz** [comment]
Done in #324.
