### ISSUE TITLE
perf.yml files created with executable bit set

### ISSUE THREAD

**Issue by PeterJCLaw** [adamchainz/django-perf-rec#264]
I've just spotted that my test.perf.yml are marked executable in git, which is surprising as they're YAML files (which aren't executable).

As far as I know, none of the the developers are using Windows (only a mixture of macOS and Linux), so I'm not expecting this to be a platform thing on our end.

Is this expected?

**Comment by adamchainz** [comment]
I don't believe django-perf-rec does anything that would make the files executable. All the modification code is here: https://github.com/adamchainz/django-perf-rec/blob/master/src/django_perf_rec/yaml.py .

If you delete a file and rerun the tests to generate it, does it return as executable? Are you running your tests with a local Python, rather than through Docker or a VM?

**Comment by PeterJCLaw** [comment]
I'm running the tests with a local Python (3.5.9 on Ubuntu 18.04 LTS).
If I add a new test to the snapshot then the mode doesn't change, however if I regenerate the file then it does.

I agree from a quick look at that code that nothing stands out as likely to cause this, it's most odd.

**Comment by PeterJCLaw** [comment]
Ah, it looks like [`os.open`](https://docs.python.org/3/library/os.html#os.open) has a default `mode` of `0o777` -- that'll be what's causing this.

**Comment by PeterJCLaw** [comment]
It looks like `django.core.files.locks` functions can be passed a file object (rather than specifically an `fd`) -- is there a reason not to do that? That feels like it would simplify the code too.

**Comment by adamchainz** [comment]
Pretty sure all that does under the hood is get the fd off the file object

IIRC, using `os.open()` is necessary to pass the right flags for creating the file without conflict.
